[*]
version = 1

# ============================================================
# CPU
# ============================================================

gpu-layers = 0
fit = off
flash-attn = off

jinja = 1
reasoning = on

ctx-size = 131072
parallel = 1
reasoning-budget = 8192

# CPU threads
t = 8

# Prompt / slot cache
cache-idle-slots = 1
cache-prompt = 1
cache-reuse = 256
kv-unified = 1

# Quantized KV cache
cache-type-k = f16
cache-type-v = f16

log-verbosity = 4
metrics = 1


# ============================================================
# LFM 2.5 2.6B
# ============================================================

[LFM2.5-2.6B]
model = /home/elpoeta/AI/models/llama/liquid/LFM2.5-2.6B-Q4_K_M.gguf

temp = 0.1
top-p = 1.0
top-k = 50
min-p = 0.0

repeat-penalty = 1.0
presence-penalty = 0.0

load-mode = none
alias = lfm2.5-2.6b

# ============================================================
# Ornith 1.5 9B
# ============================================================

[Ornith 1.5 9B]
model = /home/elpoeta/AI/models/llama/ornith/Ornith-1.5-9B-Q4_K_M.gguf

temp = 0.6
top-p = 0.95
top-k = 20
min-p = 0.0

repeat-penalty = 1.0
presence-penalty = 0.0

load-mode = none
alias = ornith-1.5-9B

# ============================================================
# GEMMA 4 E2B
# QAT UD-Q4_K_XL
# ============================================================

[Gemma-4-E2B]
model = /home/elpoeta/AI/models/llama/gemma4/gemma-4-E2B-it-qat-UD-Q4_K_XL.gguf

temp = 1.0
top-p = 0.95
top-k = 64
min-p = 0.0

repeat-penalty = 1.0
presence-penalty = 0.0

load-mode = none
alias = gemma4-e2b


# ============================================================
# GEMMA 4 E2B
# MTP
# ============================================================

[Gemma-4-E2B-MTP]
model = /home/elpoeta/AI/models/llama/gemma4/gemma-4-E2B-it-qat-UD-Q4_K_XL.gguf

model-draft = /home/elpoeta/AI/models/llama/gemma4/mtp-gemma-4-E2B-it-Q4_0.gguf

spec-type = draft-mtp
spec-draft-n-max = 4

temp = 1.0
top-p = 0.95
top-k = 64
min-p = 0.0

repeat-penalty = 1.0
presence-penalty = 0.0

load-mode = none
alias = gemma4-e2b-mtp


# ============================================================
# GEMMA 4 E2B
# VISION
# ============================================================

[Gemma-4-E2B-Vision]
model = /home/elpoeta/AI/models/llama/gemma4/gemma-4-E2B-it-qat-UD-Q4_K_XL.gguf

mmproj = /home/elpoeta/AI/models/llama/gemma4/mmproj-BF16.gguf

image-min-tokens = 1024

temp = 1.0
top-p = 0.95
top-k = 64
min-p = 0.0

repeat-penalty = 1.0
presence-penalty = 0.0

load-mode = none
alias = gemma4-e2b-vision


# ============================================================
# QWEN 3.5 2B
# MTP IS BUILT INTO THE GGUF
# ============================================================

[Qwen-3.5-2B]
model = /home/elpoeta/AI/models/llama/qwen3_5/Qwen3.5-2B-UD-Q4_K_XL.gguf

temp = 1.0
top-p = 0.95
top-k = 20
min-p = 0.0

repeat-penalty = 1.0
presence-penalty = 1.5

load-mode = none
alias = qwen3.5-2b


# ============================================================
# QWEN 3.5 2B
# MTP
#
# MTP IS MERGED INTO THE GGUF
# NO model-draft REQUIRED
# ============================================================

[Qwen-3.5-2B-MTP]
model = /home/elpoeta/AI/models/llama/qwen3_5/Qwen3.5-2B-UD-Q4_K_XL.gguf

spec-type = draft-mtp
spec-draft-n-max = 6

temp = 1.0
top-p = 0.95
top-k = 20
min-p = 0.0

repeat-penalty = 1.0
presence-penalty = 1.5

load-mode = none
alias = qwen3.5-2b-mtp


# ============================================================
# QWEN 3.5 2B
# VISION
# ============================================================

[Qwen-3.5-2B-Vision]
model = /home/elpoeta/AI/models/llama/qwen3.5/Qwen3.5-2B-UD-Q4_K_XL.gguf

mmproj = /home/elpoeta/AI/models/llama/qwen3_5/mmproj2B-BF16.gguf

image-min-tokens = 1024

temp = 1.0
top-p = 0.95
top-k = 20
min-p = 0.0

repeat-penalty = 1.0
presence-penalty = 0.0

load-mode = none
alias = qwen3.5-2b-vision


# ============================================================
# QWEN 3.5 4B
# MTP IS BUILT INTO THE GGUF
# ============================================================

[Qwen-3.5-4B]
model = /home/elpoeta/AI/models/llama/qwen3_5/Qwen3.5-4B-Q4_K_M.gguf

temp = 1.0
top-p = 0.95
top-k = 20
min-p = 0.0

repeat-penalty = 1.0
presence-penalty = 1.5

load-mode = none
alias = qwen3.5-4b


# ============================================================
# QWEN 3.5 4B
# MTP
#
# MTP IS MERGED INTO THE GGUF
# NO model-draft REQUIRED
# ============================================================

[Qwen-3.5-4B-MTP]
model = /home/elpoeta/AI/models/llama/qwen3_5/Qwen3.5-4B-Q4_K_M.gguf

spec-type = draft-mtp
spec-draft-n-max = 6

temp = 1.0
top-p = 0.95
top-k = 20
min-p = 0.0

repeat-penalty = 1.0
presence-penalty = 1.5

load-mode = none
alias = qwen3.5-4b-mtp


# ============================================================
# QWEN 3.5 4B
# VISION
# ============================================================

[Qwen-3.5-4B-Vision]
model = /home/elpoeta/AI/models/llama/qwen3_5/Qwen3.5-4B-Q4_K_M.gguf

mmproj = /home/elpoeta/AI/models/llama/qwen3_5/mmproj-BF16.gguf

image-min-tokens = 1024

temp = 1.0
top-p = 0.95
top-k = 20
min-p = 0.0

repeat-penalty = 1.0
presence-penalty = 0.0

load-mode = none
alias = qwen3.5-4b-vision
