[*]
version = 1
gpu-layers = all
fit = off
flash-attn = on
jinja = 1
reasoning = on
ctx-size = 131072
parallel = 1
reasoning-budget = 8192
t = 8
cache-idle-slots = 1
cache-prompt = 1
cache-reuse = 256
kv-unified = 1
log-verbosity = 4
metrics = 1

[Ornith-1.5]
model = /home/elpoeta/AI/models/llama/ornith/Ornith-1.5-35B-Q6_K.gguf
ncmoe = 35
numa = distribute
temp = 0.6
top-p = 0.95
top-k = 20
min-p = 0.2
cache-type-k = q8_0
cache-type-v = q8_0
repeat-penalty = 1.0
presence-penalty = 1.5
load-mode = none
alias = ornith

[Ornith-1.5-Vision]
model = /home/elpoeta/AI/models/llama/ornith/Ornith-1.5-35B-Q6_K.gguf
mmproj = /home/elpoeta/AI/models/llama/ornith/mmproj-Ornith-1.5-35B-BF16.gguf
image-min-tokens = 1024
ncmoe = 39
numa = distribute
temp = 0.6
top-p = 0.95
top-k = 20
min-p = 0.2
cache-type-k = q8_0
cache-type-v = q8_0
repeat-penalty = 1.0
presence-penalty = 1.5
load-mode = none
alias = ornith-vision

[Ornith-1.5-Apex]
model = /home/elpoeta/AI/models/llama/ornith/apex/Ornith-1.5-35B-A3B-APEX-MTP-I-Balanced.gguf
ncmoe = 37
numa = distribute
temp = 0.6
top-p = 0.95
top-k = 20
min-p = 0.2
spec-type = draft-mtp
spec-draft-n-max = 2
cache-type-k = q8_0
cache-type-v = q8_0
repeat-penalty = 1.0
presence-penalty = 1.5
load-mode = none
alias = ornith-apex

[Ornith-1.5-Vision-Apex]
model = /home/elpoeta/AI/models/llama/ornith/apex/Ornith-1.5-35B-A3B-APEX-MTP-I-Balanced.gguf
mmproj = /home/elpoeta/AI/models/llama/ornith/apex/mmproj.gguf
image-min-tokens = 1024
ncmoe = 39
numa = distribute
temp = 0.6
top-p = 0.95
top-k = 20
min-p = 0.2
spec-type = draft-mtp
spec-draft-n-max = 2
cache-type-k = q8_0
cache-type-v = q8_0
repeat-penalty = 1.0
presence-penalty = 1.5
load-mode = none
alias = ornith-apex-vision

[Gemma-4-26B-A-4B]
model = /home/elpoeta/AI/models/llama/gemma4/gemma-4-26B_q4_0-it.gguf
#mmproj = /home/elpoeta/AI/models/llama/gemma4/mmproj-BF16.gguf
#model-draft = /home/elpoeta/AI/models/llama/gemma4/.gguf
temp = 1.0
top-p = 0.95
top-k = 64
ncmoe = 28
numa = distribute
repeat-penalty = 1.0
presence-penalty = 0.0
load-mode = none
alias = gemma4-26B




